# Site settings
title: Paper reivew
email: spnova12@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I read papers.
baseurl: ""  # the subpath of your site, e.g. /blog/
url: "http://paperviewer.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  paperviewer
safe: true

# Build settings
markdown: kramdown
permalink: pretty
